# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb866e9da65a17f0878e874f3a04bf9c0030f99787bc342e672759a1c2df3f24e0571ca031e216071beb7ea8d8b21c6345a51ec6ee5307b10c8beaeee23cb8cf

test:
  secret_key_base: 0b5fb75b3cc956ce1347f7909f97ee43f412bd979d016be149abae0649efeebaafe474511b05cfa49d66d8409e6e5ff684bb72dea18a460648ee04d43e112125

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
